######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 5 22:14:59 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h util.h
FORMS += dialog.ui
SOURCES += dialog.cpp main.cpp util.cpp
QMAKE_CXXFLAGS += -std=c++0x
